<?php

$sLangName = 'Deutsch';

$aLang = [
    'charset' => 'UTF-8', // Supports german language specific chars like: ä, ö. ß, etc.
    'ciadminform'                                       => 'Formulare',
    'ciadminformelements'                               => 'Formular Eingabefelder',
    'CI_FORM_ALL'                                       => 'Alle',
    'TOOLTIPS_NEW_ATTACHMENT'                           => 'Neues Formular',
    'tbclciadminformmain'                               => 'Stamm',
    'tbclciadminformelementmain'                        => 'Stamm',
    'tbclciadminformelement'                            => 'Eingabeelemente',
    'GENERAL_IMAGE'                                     => 'Bild',
    'GENERAL_ROUTE'                                     => 'Route wählen (Mehrfachauswahl)',
    'HELP_FORMS_STATICURLS'                             => 'Auf den ausgewählten Seiten, wird der Slider ausgegeben. Mehrfachauswahl mit STRG+Klick möglich',
    'EDIT_FORM'                                         => 'Hotspots bearbeiten',

    'CI_FORM_CODE'                                      => 'Template-Code',
    'CI_FORM_BANNER_CODE'                               => 'Slider-Code',
    'CI_FORM_STARTPAGE'                                 => 'In ausgewählten Routen anzeigen (Und in den zugewiesenen Kategorien)',
    'CI_FORM_CATEGORY'                                  => 'Nur in Kategorien anzeigen',

    'FORM_CSSCLASS'                                     => 'Frontend CSS Klasse',
    'HELP_FORM_CSSCLASS'                                => 'Mit dieser Funktion, kann die Ausgabe via CSS angepasst werden.',

    'GENERAL_FORM_ACTION'                               => 'Weiterleitungsziel',
    'GENERAL_AJAX_SORT_OXLABEL'                         => 'Feldbezeichnung',
    'HELP_GENERAL_FORM_ACTION'                          => 'Kann ein Link oder eine CMS Seite sein.',

    'FORMBUILDER_LABEL_OXTYPE'                          => 'Feldtyp',
    'FORMBUILDER_LABEL_OXTYPE_HELP'                     => 'Bitte wählen Sie den Typ des Formularfelds.',
    'FORMBUILDER_LABEL_OXALIAS'                         => 'Alias',
    'FORMBUILDER_LABEL_OXALIAS_HELP'                    => 'Alias mit dem dieser Eintrag identifiziert werden kann.',
    'FORMBUILDER_LABEL_OXHTMLTEMPLATE'                  => 'HTML-Template (Ohne .tpl)',
    'FORMBUILDER_LABEL_OXHTMLTEMPLATE_HELP'             => 'Dieses Template wird, falls es vorhanden, aus Application/view/AKTIVES_THEME/email/formbuilder/ geladen.',
    'FORMBUILDER_LABEL_OXSENDFORM'                      => 'Formular senden',
    'FORMBUILDER_LABEL_OXSENDFORM_HELP'                 => 'Soll das Formular gesendet werden?',
    'FORMBUILDER_LABEL_OXRECEIVER'                      => 'Empfänger',
    'FORMBUILDER_LABEL_OXRECEIVER_HELP'                 => 'Sie können hier kommagetrennt E-Mail-Adressen von Empfängern sein.',
    'FORMBUILDER_LABEL_OXSUBJECT'                       => 'Betreff',
    'FORMBUILDER_LABEL_OXSUBJECT_HELP'                  => 'Bitte geben Sie den Betreff für dieses Formular an.',
    'FORMBUILDER_LABEL_OXCONTENT'                       => 'E-Mail Inhalt',
    'FORMBUILDER_LABEL_OXCONTENT_HELP'                  => 'Bitte geben Sie hier den Text der E-Mail ein. Es werden Smartyvariablen in unterstützt.',
    'FORMBUILDER_LABEL_OXSORT'                          => 'Sortieren',
    'FORMBUILDER_LABEL_OXSORT_HELP'                     => 'Das Feld mit der niedrigsten Sortierung, wird an erster Stelle ausgegeben.',
    'FORMBUILDER_LABEL_OXACTIVE'                        => 'Aktiv',
    'FORMBUILDER_LABEL_OXACTIVE_HELP'                   => 'Dieser Eintrag ist aktiv.',
    'FORMBUILDER_LABEL_OXACTIVEFROM'                    => 'Von',
    'FORMBUILDER_LABEL_OXACTIVEFROM_HELP'               => 'Bitte ein Datum im folgenden Format eingeben: 0000-00-00 00:00:00.',
    'FORMBUILDER_LABEL_OXACTIVETO'                      => 'Bis',
    'FORMBUILDER_LABEL_OXACTIVETO_HELP'                 => 'Bitte ein Datum im folgenden Format eingeben: 0000-00-00 00:00:00.',
    'FORMBUILDER_LABEL_OXACTION'                        => 'Weiterleitungsziel',
    'FORMBUILDER_LABEL_OXACTION_HELP'                   => 'Auf diese Seite wird weitergeleitet.',
    'FORMBUILDER_LABEL_OXCSSCLASS'                      => 'CSS-Klasse',
    'FORMBUILDER_LABEL_OXCSSCLASS_HELP'                 => 'Diese Klasse kann verwendet werden, um den Stil des Formulares zu bestimmen.',
    'FORMBUILDER_LABEL_OXTITLE'                         => 'Feldname',
    'FORMBUILDER_LABEL_OXTITLE_HELP'                    => 'Der Feldname ist ein eindeutiger Name zur Identifizierung des Feldes.',
    'FORMBUILDER_LABEL_OXVALUE'                         => 'Feldwert',
    'FORMBUILDER_LABEL_OXVALUE_HELP'                    => 'Dieser Wert, wird für das Eingabefeld vorausgefüllt.',
    'FORMBUILDER_LABEL_OXLABEL'                         => 'Feldbezeichnung',
    'FORMBUILDER_LABEL_OXLABEL_HELP'                    => 'Die Feldbezeichnung wird auf der Webseite angezeigt, normalerweise links neben oder oberhalb des Feldes.',
    'FORMBUILDER_LABEL_OXREQUIRED'                      => 'Pflichtfeld',
    'FORMBUILDER_LABEL_OXREQUIRED_HELP'                 => 'Das Feld muss zum Abschicken des Formulars ausgefüllt werden.',
    'FORMBUILDER_LABEL_OXVALIDATION'                    => 'Eingabeprüfung',
    'FORMBUILDER_LABEL_OXVALIDATION_HELP'               => 'Die Eingaben anhand eines regulären Ausdrucks prüfen.',
    'FORMBUILDER_LABEL_OXPLACEHOLDER'                   => 'Platzhalter',
    'FORMBUILDER_LABEL_OXPLACEHOLDER_HELP'              => 'Dieser Text wird angezeigt solange das Feld noch nicht ausgefüllt wurde (benötigt HTML5).',
    'FORMBUILDER_LABEL_OXOPTIONS'                       => 'Optionenliste',
    'FORMBUILDER_LABEL_OXOPTIONS_HELP'                  => 'Geben Sie hier Daten nach dem Muster key => value ein.',

    'FORMBUILDER_VALUE_OXTYPE_text'                     => 'Textfeld',
    'FORMBUILDER_VALUE_OXTYPE_default'                  => 'Textfeld',
    'FORMBUILDER_VALUE_OXTYPE_textarea'                 => 'Mehrzeiliges Textfeld',
    'FORMBUILDER_VALUE_OXTYPE_select'                   => 'Auswahlmenü',
    'FORMBUILDER_VALUE_OXTYPE_checkbox'                 => 'Checkbox(en)',
    'FORMBUILDER_VALUE_OXTYPE_radio'                    => 'Radiobutton-Liste',
    'FORMBUILDER_VALUE_OXTYPE_submit'                   => 'Absendefeld',

    'FORMBUILDER_VALUE_OXVALIDATION__blank'             => 'Validierung wählen',
    'FORMBUILDER_VALUE_OXVALIDATION_number'             => 'Numerische Eingabe',
    'FORMBUILDER_VALUE_OXVALIDATION_email'              => 'E-Mail',

    'FORMBUILDER_WARNING_NO_FORM_SELECTED'              => 'Bitte wählen Sie ein Formular aus.',
    'FORMBUILDER_WARNING_NO_FIELDS_APPLYED'             => 'Bitte weisen Sie diesem Formular zuerst Eingabefelder hinzu.',

    'FORMBUILDER_FIELDCONFIG_HEADLINE'                  => 'Eingabefelder einordnen',
    'FORMBUILDER_HELP_NOT_APPLIED_ITEMS'                => 'Noch nicht zugewiesene Eingabefelder',
    'FORMBUILDER_HELP_DRAG_ITEMS_INTO_FIELDSETS'        => 'Ziehen Sie die Felder in die Fieldsets nach unten.',

];